# Generated by Django 3.2.7 on 2021-09-06 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learneranswer',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='learneranswer',
            name='student',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='course',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='user',
        ),
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='course',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='takenquiz',
            name='learner',
        ),
        migrations.RemoveField(
            model_name='takenquiz',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='course',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='user',
        ),
        migrations.RemoveField(
            model_name='learner',
            name='quizzes',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='LearnerAnswer',
        ),
        migrations.DeleteModel(
            name='Notes',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='TakenQuiz',
        ),
        migrations.DeleteModel(
            name='Tutorial',
        ),
    ]
